# Указываем базовый образ для архитектуры ARM64
FROM ubuntu:20.04

# Метаданные об обслуживании образа
LABEL maintainer="mabate@mit.edu"

# Устанавливаем переменную окружения, чтобы предотвратить запросы интерактивного ввода
ENV DEBIAN_FRONTEND=noninteractive

ENV DIRPATH /root/
WORKDIR $DIRPATH

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      apt-utils \
      cmake \
      wget \
      pkg-config \
      tar \
      xvfb \
      build-essential unzip bzip2 \
      libjpeg-dev libpng-dev libtiff-dev \
      libvtk7-dev \
      libgtk-3-dev \
      libparmetis-dev \
      libatlas-base-dev gfortran \
      libtbb2-dev git ca-certificates \
      libopenjpip7 \
      libopenjp2-tools \
      libopenjpip-dec-server \
      libopenjpip-server \
      libgflags-dev \
      python3 \
      libgoogle-glog-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Скачиваем и устанавливаем Boost
RUN wget --no-check-certificate https://boostorg.jfrog.io/artifactory/main/release/1.82.0/source/boost_1_82_0.tar.bz2 && \
    tar -xjf boost_1_82_0.tar.bz2 && \
    cd boost_1_82_0 &&  \
    ./bootstrap.sh --prefix=/usr/local/boost --with-libraries=all && \
    ./b2 install -j$(nproc) && \
    cd .. 

RUN echo "/usr/local/boost/lib" > /etc/ld.so.conf.d/boost.conf && \
    ldconfig

# Экспортируем переменную среды BOOST_ROOT
ENV BOOST_ROOT /usr/local/boost

ADD https://api.github.com/repos/borglab/gtsam/git/refs/heads/develop version.json
RUN git clone https://github.com/borglab/gtsam.git && \
    cd gtsam && \
    git checkout tags/4.1.1 && \
    mkdir build && \
    cd build && \
    cmake \
          -DCMAKE_INSTALL_PREFIX=/usr/local \
          -DCMAKE_BUILD_TYPE=Release \
          -DGTSAM_POSE3_EXPMAP=ON \
          -DGTSAM_ROT3_EXPMAP=ON \
          -DGTSAM_TANGENT_PREINTEGRATION=OFF \
          -DGTSAM_USE_SYSTEM_EIGEN=OFF  \
          .. && \
    make -j$(nproc) install

ENV LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

# Клонирование репозиториев OpenCV и OpenCV_contrib
RUN git clone https://github.com/opencv/opencv.git && \
    git clone https://github.com/opencv/opencv_contrib.git && \
    cd opencv_contrib && \
    git checkout tags/4.5.5 && \
    cd .. && \
    cd opencv && \
    git checkout tags/4.5.5 && \
    mkdir build && \
    cd build && \
    cmake \
    -DCMAKE_INSTALL_PREFIX=/usr/local \
    -DCMAKE_BUILD_TYPE=Release \
    -DWITH_TBB=ON \
    -DWITH_VTK=ON \
    -DOPENCV_EXTRA_MODULES_PATH=$DIRPATH/opencv_contrib/modules \
    .. && \
make -j$(nproc) install

# Загружаем версию разработки репозитория Open_GV
RUN git clone https://github.com/laurentkneip/opengv.git && \
    cd opengv && \
    mkdir build && \
    cd build && \
    cmake \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=/usr/local \
          -DEIGEN_INCLUDE_DIR=$DIRPATH/gtsam/gtsam/3rdparty/Eigen \
          -DEIGEN_INCLUDE_DIRS=$DIRPATH/gtsam/gtsam/3rdparty/Eigen \
          .. && \
    make -j$(nproc) install

#RUN cd opengv/build && make test

# Клонируем репозиторий DBoW2 и устанавливаем его
COPY .patches/fix_vocab.patch dbow2.patch
RUN git clone https://github.com/dorian3d/DBoW2.git && \
    cd DBoW2 && \
    git apply ../dbow2.patch && \
    mkdir build && \
    cd build && \
    cmake \
         .. && \
    make -j$(nproc) install

# Загружаем версию разработки репозитория RobustPGO
RUN git clone https://github.com/MIT-SPARK/Kimera-RPGO.git && \
    cd Kimera-RPGO && \
    mkdir build && \
    cd build && \
    cmake \
          .. && \
    make -j$(nproc) install
